/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.24
 * Generated at: 2019-08-30 10:53:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.resources;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("<title>BBR Login</title>\r\n");
      out.write("<meta name=\"description\" content=\"BBR Login\">\r\n");
      out.write("<meta name=\"keywords\" content=\"BBR Login\">\r\n");
      out.write("<link href=\"\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("\tbody,p,div,ul,li,h1,h2,h3,h4,h5,h6{\r\n");
      out.write("\t\tmargin:0;\r\n");
      out.write("\t\tpadding: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tbackground: #E9E9E9; \r\n");
      out.write("\t}\r\n");
      out.write("\t#login{\r\n");
      out.write("\t\twidth: 400px;\r\n");
      out.write("\t\theight: 270px;\r\n");
      out.write("\t\tbackground: #FFF;\r\n");
      out.write("\t\tmargin:200px auto;\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t}\r\n");
      out.write("\t#login h1{\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t\tleft:120px;\r\n");
      out.write("\t\ttop:-40px;\r\n");
      out.write("\t\tfont-size:21px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#login form p{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t#username{\r\n");
      out.write("\t\tbackground:url(../../images/user.png) rgba(0,0,0,.1) no-repeat;\r\n");
      out.write("\t\twidth: 200px;\r\n");
      out.write("\t\theight: 30px;\r\n");
      out.write("\t\tborder:solid #ccc 1px;\r\n");
      out.write("\t\tborder-radius: 3px;\r\n");
      out.write("\t\tpadding-left: 32px;\r\n");
      out.write("\t\tmargin-top: 50px;\r\n");
      out.write("\t\tmargin-bottom: 30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#password{\r\n");
      out.write("\t\tbackground: url(../../images/pwd.png) rgba(0,0,0,.1) no-repeat;\r\n");
      out.write("\t\twidth: 200px;\r\n");
      out.write("\t\theight: 30px;\r\n");
      out.write("\t\tborder:solid #ccc 1px;\r\n");
      out.write("\t\tborder-radius: 3px;\r\n");
      out.write("\t\tpadding-left: 32px;\r\n");
      out.write("\t\tmargin-bottom: 30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#submit{\r\n");
      out.write("\t\twidth: 232px;\r\n");
      out.write("\t\theight: 30px;\r\n");
      out.write("\t\tbackground: rgba(0,0,0,.1);\r\n");
      out.write("\t\tborder:solid #ccc 1px;\r\n");
      out.write("\t\tborder-radius: 3px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#submit:hover{\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\tbackground:#D8D8D8;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"login\">\r\n");
      out.write("<h1>BBR Login</h1>\r\n");
      out.write("\t<form action=\"Login\" method=\"post\">\r\n");
      out.write("\t\t<p><input type=\"text\" name=\"username\" id=\"username\" placeholder=\"username\"></p>\r\n");
      out.write("\t\t<p><input type=\"password\" name=\"password\" id=\"password\" placeholder=\"password\"></p>\r\n");
      out.write("\t\t<p><input type=\"submit\" id=\"submit\" value=\"Login\"></p>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t<center><p><a href=\"Download?filename=help.docx\" target=\"_blank\">help</a></p></center>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
